import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";

import PropertyContainer from "../components/PropertyContainer";

import { baseUrl, fetchApi } from "../utils/fetchApi";

export default function Home({ forSale }) {
   return (
      <div className="">
         <Head>
            <title>Real State Nextjs Application</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

          <Hero/>
         <div className="container w-11/12 mx-auto">
            <PropertyContainer properties={forSale} />
         </div>
      </div>
   );
}

export const getStaticProps = async () => {
   const forSale = await fetchApi(
      `${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-sale&hitsPerPage=9`
   );
   // const forRent = await fetchApi(`${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-rent&hitsPerPage=9`);

   return {
      props: {
         forSale: forSale?.hits,
         // forRent : forRent?.hits,
      },
   };
};
